final-plataforma/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using final_plataforma.Data;
using final_plataforma.Models;
using Microsoft.AspNetCore.Http;

namespace final_plataforma.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly final_plataformaContext _context;

        public CategoriasController(final_plataformaContext context)
        {
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
            string id = HttpContext.Session.GetString("id_admin");

            if (id == null)
            {
                return RedirectToAction("Index", "Login");
            }

            return View(await _context.categorias.ToListAsync());
        }

        // GET: Categorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.categorias
                .FirstOrDefaultAsync(m => m.id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        public IActionResult Create()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.categorias.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre")] Categoria categoria)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id != categoria.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.categorias
                .FirstOrDefaultAsync(m => m.id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoria = await _context.categorias.FindAsync(id);
            _context.categorias.Remove(categoria);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaExists(int id)
        {
            return _context.categorias.Any(e => e.id == id);
        }
    }
}

final-plataforma/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using final_plataforma.Data;
using final_plataforma.Models;
using Microsoft.AspNetCore.Http;

namespace final_plataforma.Controllers
{
    public class ComprasController : Controller
    {
        private readonly final_plataformaContext _context;

        public ComprasController(final_plataformaContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            // _context.producto_compra.Load();
            // _context.compras.Load();
            _context.producto.Load();
            _context.usuarios.Load();
            _context.usuario_compra.Load();
            var lista = await _context.compras.Include(C => C.producto_compra).ToListAsync();
            return View(lista);
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.compras
                .FirstOrDefaultAsync(m => m.id == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,total")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                _context.Add(compra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,total")] Compra compra)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id != compra.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.compras
                .FirstOrDefaultAsync(m => m.id == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compra = await _context.compras.FindAsync(id);
            _context.compras.Remove(compra);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(int id)
        {
            return _context.compras.Any(e => e.id == id);
        }
    }
}

final-plataforma/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using final_plataforma.Data;
using final_plataforma.Models;
using Microsoft.AspNetCore.Http;

namespace final_plataforma.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly final_plataformaContext _context;

        public UsuariosController(final_plataformaContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View(await _context.Usuario.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,dni,nombre,apellido,mail,password,tipo,cuil,id_carro")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                Carro carro = new Carro();
                usuario.carro = carro;
                _context.Add(carro);
                usuario.habilitado = true; //comentar para que deba ser habilitado por un admin
                usuario.intentos = 3;
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                usuario.id_carro = carro.id;
                _context.usuarios.Update(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,dni,nombre,apellido,mail,password,tipo,cuil,id_carro,habilitado,intentos")] Usuario usuario)
        {
            if (id != usuario.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    usuario.intentos = 3;
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            _context.Usuario.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuario.Any(e => e.id == id);
        }
    }
}

final-plataforma/Views/Usuarios/Create.cshtml
@model final_plataforma.Models.Usuario

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="dni" class="control-label"></label>
                <input asp-for="dni" class="form-control" />
                <span asp-validation-for="dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido" class="control-label"></label>
                <input asp-for="apellido" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mail" class="control-label"></label>
                <input asp-for="mail" class="form-control" />
                <span asp-validation-for="mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipo" class="control-label"></label>
                <input asp-for="tipo" class="form-control" />
                <span asp-validation-for="tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cuil" class="control-label"></label>
                <input asp-for="cuil" class="form-control" />
                <span asp-validation-for="cuil" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none;">
                <label asp-for="id_carro" class="control-label"></label>
                <input asp-for="id_carro" class="form-control"  value="0"/>
                <span asp-validation-for="id_carro" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none;">
                <label asp-for="habilitado" class="control-label"></label>
                <input asp-for="habilitado" class="form-control" value="1" />
                <span asp-validation-for="habilitado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

final-plataforma/Views/Usuarios/Delete.cshtml
@model final_plataforma.Models.Usuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cuil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cuil)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id_carro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id_carro)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">volver</a>
    </form>
</div>

final-plataforma/Views/Usuarios/Details.cshtml
@model final_plataforma.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cuil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cuil)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id_carro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id_carro)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">volver</a>
</div>

final-plataforma/Views/Usuarios/Index.cshtml
@model IEnumerable<final_plataforma.Models.Usuario>

@{
    ViewData["Title"] = "usuarios";
}
<div>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<h1>🙍‍♂️ usuarios</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.dni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cuil)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.id_carro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.habilitado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.intentos)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.dni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cuil)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.id_carro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.habilitado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.intentos)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>