final-plataforma/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using final_plataforma.Data;
using final_plataforma.Models;
using Microsoft.AspNetCore.Http;

namespace final_plataforma.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly final_plataformaContext _context;

        public CategoriasController(final_plataformaContext context)
        {
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
            string id = HttpContext.Session.GetString("id_admin");

            if (id == null)
            {
                return RedirectToAction("Index", "Login");
            }

            return View(await _context.categorias.ToListAsync());
        }

        // GET: Categorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.categorias
                .FirstOrDefaultAsync(m => m.id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        public IActionResult Create()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.categorias.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre")] Categoria categoria)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id != categoria.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.categorias
                .FirstOrDefaultAsync(m => m.id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoria = await _context.categorias.FindAsync(id);
            _context.categorias.Remove(categoria);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaExists(int id)
        {
            return _context.categorias.Any(e => e.id == id);
        }
    }
}

final-plataforma/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using final_plataforma.Data;
using final_plataforma.Models;
using Microsoft.AspNetCore.Http;

namespace final_plataforma.Controllers
{
    public class ComprasController : Controller
    {
        private readonly final_plataformaContext _context;

        public ComprasController(final_plataformaContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            // _context.producto_compra.Load();
            // _context.compras.Load();
            _context.producto.Load();
            _context.usuarios.Load();
            _context.usuario_compra.Load();
            var lista = await _context.compras.Include(C => C.producto_compra).ToListAsync();
            return View(lista);
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.compras
                .FirstOrDefaultAsync(m => m.id == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,total")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                _context.Add(compra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,total")] Compra compra)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id != compra.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.compras
                .FirstOrDefaultAsync(m => m.id == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compra = await _context.compras.FindAsync(id);
            _context.compras.Remove(compra);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(int id)
        {
            return _context.compras.Any(e => e.id == id);
        }
    }
}

final-plataforma/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using final_plataforma.Data;
using final_plataforma.Models;
using Microsoft.AspNetCore.Http;

namespace final_plataforma.Controllers
{
    public class ProductosController : Controller
    {
        private readonly final_plataformaContext _context;

        public ProductosController(final_plataformaContext context)
        {
            _context = context;
        }

        // GET: Productoes
        public async Task<IActionResult> Index()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var final_plataformaContext = _context.producto.Include(p => p.categoria);
            return View(await final_plataformaContext.ToListAsync());
        }

        // GET: Productoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.producto
                .Include(p => p.categoria)
                .FirstOrDefaultAsync(m => m.id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productoes/Create
        public IActionResult Create()
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            ViewData["id_categoria"] = new SelectList(_context.categorias, "id", "id");
            return View();
        }

        // POST: Productoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre,precio,cantidad,id_categoria")] Producto producto)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_categoria"] = new SelectList(_context.categorias, "id", "id", producto.id_categoria);
            return View(producto);
        }

        // GET: Productoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["id_categoria"] = new SelectList(_context.categorias, "id", "id", producto.id_categoria);
            return View(producto);
        }

        // POST: Productoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre,precio,cantidad,id_categoria")] Producto producto)
        {
            if (id != producto.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_categoria"] = new SelectList(_context.categorias, "id", "id", producto.id_categoria);
            return View(producto);
        }

        // GET: Productoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string idAdmin = HttpContext.Session.GetString("id_admin");

            if (idAdmin == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.producto
                .Include(p => p.categoria)
                .FirstOrDefaultAsync(m => m.id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _context.producto.FindAsync(id);
            _context.producto.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.producto.Any(e => e.id == id);
        }
    }
}

final-plataforma/Views/Productos/Create.cshtml
@model final_plataforma.Models.Producto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidad" class="control-label"></label>
                <input asp-for="cantidad" class="form-control" />
                <span asp-validation-for="cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="id_categoria" class="control-label"></label>
                <select asp-for="id_categoria" class ="form-control" asp-items="ViewBag.id_categoria"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

final-plataforma/Views/Productos/Delete.cshtml
@model final_plataforma.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.categoria.id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">volver</a>
    </form>
</div>

final-plataforma/Views/Productos/Details.cshtml
@model final_plataforma.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.categoria.id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">volver</a>
</div>

final-plataforma/Views/Productos/Edit.cshtml
@model final_plataforma.Models.Producto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidad" class="control-label"></label>
                <input asp-for="cantidad" class="form-control" />
                <span asp-validation-for="cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="id_categoria" class="control-label"></label>
                <select asp-for="id_categoria" class="form-control" asp-items="ViewBag.id_categoria"></select>
                <span asp-validation-for="id_categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

final-plataforma/Views/Productos/Index.cshtml
@model IEnumerable<final_plataforma.Models.Producto>

@{
    ViewData["Title"] = "Producto";
}
<div>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<h1>📺 Productos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.categoria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoria.id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>