final-plataforma/Controllers/MercadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using final_plataforma.Data;
using final_plataforma.Models;
using Microsoft.AspNetCore.Http;

namespace final_plataforma.Controllers
{

    //ver como pasar el usuario entre pantallas
    public class MercadoController : Controller
    {
        private readonly final_plataformaContext _context;
        private int idUsuario;

        public MercadoController(final_plataformaContext context)
        {
            _context = context;
        }

        // pantalla principal donde se muestran los productos
        public IActionResult Index(string sortOrder, string nombreProd, string nombreCateg)
        {

    
            string id = HttpContext.Session.GetString("id_usuario");

            if (id==null)
            {
                return RedirectToAction("Index", "Login");
            }

            Usuario usuario = _context.usuarios.Where(U => U.id == Int32.Parse(id)).Include(U => U.carro).Include(U=>U.carro.producto_Carro).FirstOrDefault();

            //ver como cargar esta lista porque producto carro es una lista
            _context.producto.Load();

            ViewBag.nombre = usuario.nombre;

            List<int> productosEnCarro = new List<int>();
            if (usuario.carro!=null && usuario.carro.producto_Carro != null)
            {
                foreach (Producto_Carro PC in usuario.carro.producto_Carro)
                {
                    productosEnCarro.Add(PC.id_Producto);
                }
            }
            
            ViewBag.productosEnCarro = productosEnCarro.ToList();
            ViewBag.cantProductos = productosEnCarro.Count();


            ViewBag.NombreSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PrecioSortParm = sortOrder == "Precio" ? "Precio_desc" : "Precio";
            ViewBag.CantidadSortParm = sortOrder == "Cantidad" ? "cantidad_desc" : "Cantidad";
            ViewBag.CategoriaSortParm = sortOrder == "Categoria" ? "categoria_desc" : "Categoria";

            var productos = _context.producto.Include(p => p.categoria);
            var listaProductos = productos.Where(P => P.cantidad > 0);

            if (!String.IsNullOrEmpty(nombreProd))
            {
                listaProductos = listaProductos.Where(s => s.nombre.Contains(nombreProd));
            }

            if (!String.IsNullOrEmpty(nombreCateg))
            {
                listaProductos = listaProductos.Where(s => s.categoria.nombre.Contains(nombreCateg));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    listaProductos = listaProductos.OrderByDescending(s => s.nombre);
                    break;
                case "Precio":
                    listaProductos = listaProductos.OrderBy(s => s.precio);
                    break;
                case "Precio_desc":
                    listaProductos = listaProductos.OrderByDescending(s => s.precio);
                    break;
                case "Cantidad":
                    listaProductos = listaProductos.OrderBy(s => s.cantidad);
                    break;
                case "cantidad_desc":
                    listaProductos = listaProductos.OrderByDescending(s => s.cantidad);
                    break;
                case "Categoria":
                    listaProductos = listaProductos.OrderBy(s => s.categoria.nombre);
                    break;
                case "categoria_desc":
                    listaProductos = listaProductos.OrderByDescending(s => s.categoria.nombre);
                    break;
                default:
                    listaProductos = listaProductos.OrderBy(s => s.nombre);
                    break;
            }
            return View(listaProductos);
        }

        public IActionResult Success()
        {
            string id = HttpContext.Session.GetString("id_usuario");

            if (id == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        public IActionResult Error()
        {
            string id = HttpContext.Session.GetString("id_usuario");

            if (id == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        //vista de carrito
        public IActionResult Carrito()
        {
            string id = HttpContext.Session.GetString("id_usuario");

            if (id == null)
            {
                return RedirectToAction("Index", "Login");
            }

            Int32.TryParse(id, out idUsuario);

            _context.producto.Load();
            Usuario usuario = _context.usuarios.Where(U => U.id == Int32.Parse(id)).Include(U => U.carro).Include(U => U.carro.producto_Carro).FirstOrDefault();



            if (usuario.carro.producto_Carro == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(usuario.carro);
        }

        //vista mis datos
        public async Task<IActionResult> compras()
        {
            string id = HttpContext.Session.GetString("id_usuario");

            if (id == null)
            {
                return RedirectToAction("Index", "Login");
            }
   

            _context.producto.Load();
            return View(await _context.compras  .Where(C => C.usuario_compra.Any(UC => UC.id_usuario == Int32.Parse(id)))
                                                .Include(C => C.producto_compra)
                                                .ToListAsync());

        }


        public async Task<IActionResult> Cuenta()
        {


            string id = HttpContext.Session.GetString("id_usuario");

            if (id == null)
            {
                return RedirectToAction("Index", "Login");
            }
            Int32.TryParse(id, out idUsuario);

            var usuario = await _context.Usuario.FindAsync(idUsuario);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Guardar(int id, [Bind("id,dni,nombre,apellido,mail,password,tipo,cuil,id_carro")] Usuario usuario,string nuevoPassword, string nuevoPassword2)
        {
            if (id != usuario.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (!validarPassword(usuario.password, nuevoPassword, nuevoPassword2))
                    {
                        return RedirectToAction(nameof(Cuenta));
                    }
                    usuario.habilitado = true;
                    usuario.intentos = 3;
                    usuario.password = nuevoPassword;
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Cuenta));
        }

        private bool validarPassword(string password, string nuevoPassword, string nuevoPassword2)
        {
            if (password== null || password.Length == 0) return false;
            if (nuevoPassword == null || nuevoPassword.Length == 0) return false;
            if (nuevoPassword != nuevoPassword2) return false;
            return true;
        }

        [HttpPost, ActionName("Agregar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Agregar(int id)
        {
            //session usuario
            string id1 = HttpContext.Session.GetString("id_usuario");
            Int32.TryParse(id1, out idUsuario);

            var usuario = await _context.Usuario.FindAsync(idUsuario);

            Producto_Carro producto_Carro = _context.producto_carro.Where(C => (C.id_Carro == usuario.id_carro && C.id_Producto == id)).FirstOrDefault();

            if (producto_Carro == null)
            {
                //se agrega un producto
                producto_Carro = new Producto_Carro { id_Producto = id, cantidad = 1, id_Carro = usuario.id_carro };
                _context.producto_carro.Add(producto_Carro);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Carrito));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuario.Any(e => e.id == id);
        }

        //salir
        public async Task<IActionResult> Salir()
        {
            //context.dispose
            var final_plataformaContext = _context.producto.Include(p => p.categoria);
            return View(await final_plataformaContext.ToListAsync());
        }


        /*agregar y quitar items del carrito*/

        [HttpPost, ActionName("agregaritem")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> addItem(int id)
        {
            Producto_Carro pc = _context.producto_carro.Where(PC => (PC.id == id)).FirstOrDefault();
            Producto p = _context.producto.Where(P => (P.id == pc.id_Producto)).FirstOrDefault();

            if (pc.cantidad + 1 <= p.cantidad)
            {
                pc.cantidad++;
                _context.producto_carro.Update(pc);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Carrito));
        }

final-plataforma/Controllers/RegistroController.cs
using final_plataforma.Data;
using final_plataforma.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace final_plataforma.Controllers
{
    public class RegistroController : Controller
    {
        private readonly final_plataformaContext _context;


        public RegistroController(final_plataformaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registrar([Bind("id,dni,nombre,apellido,mail,password,tipo,cuil,id_carro,habilitado")] Usuario usuario)
        {

            if (ModelState.IsValid)
            {
                Carro carro = new Carro();
                usuario.carro = carro;
                _context.Add(carro);
                usuario.habilitado = true; //comentar para que deba ser habilitado por un admin
                usuario.intentos = 3;
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                usuario.id_carro = carro.id;
                _context.usuarios.Update(usuario);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

final-plataforma/Views/Registro/Index.cshtml
@model final_plataforma.Models.Usuario

@{
    ViewData["Title"] = "Registrar";
}

<h1>Create</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Registrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="dni" class="control-label"></label>
                <input asp-for="dni" class="form-control" />
                <span asp-validation-for="dni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido" class="control-label"></label>
                <input asp-for="apellido" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mail" class="control-label"></label>
                <input asp-for="mail" class="form-control" />
                <span asp-validation-for="mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipo" class="control-label"></label>
                <input asp-for="tipo" class="form-control" />
                <span asp-validation-for="tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cuil" class="control-label"></label>
                <input asp-for="cuil" class="form-control" />
                <span asp-validation-for="cuil" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none;">
                <label asp-for="id_carro" class="control-label"></label>
                <input asp-for="id_carro" class="form-control" value="0" />
                <span asp-validation-for="id_carro" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none;">
                <label asp-for="habilitado" class="control-label"></label>
                <input asp-for="habilitado" class="form-control" value="1"/>
                <span asp-validation-for="habilitado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Mercado" asp-action="Index">volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}